version: '3.8'

services:
  # กำหนด Service ชื่อ frontend
  frontend:
    # ระบุให้ Build จาก Dockerfile ที่อยู่ใน Directory ปัจจุบัน (.)
    build: .
    # ตั้งค่า Port Mapping: ให้ Port 3000 ของเครื่อง Host เชื่อมต่อไปยัง Port 3000 ของ Container
    ports:
      - "3000:3000"
    
    